kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster1
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/16"
nodes:
  - role: control-plane
  - role: worker
  - role: worker
