kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster2
networking:
  podSubnet: "10.245.0.0/16"
  serviceSubnet: "10.97.0.0/16"
nodes:
  - role: control-plane
  - role: worker
  - role: worker
